version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: org.eclipse.microprofile.reactive-streams-operators:microprofile-reactive-streams-operators-tck
    versions:
    - "2.0"
  - dependency-name: org.eclipse.microprofile.reactive-streams-operators:microprofile-reactive-streams-operators-core
    versions:
    - "2.0"
  - dependency-name: com.vanniktech:gradle-maven-publish-plugin
    versions:
    - 0.14.0
    - 0.14.1
    - 0.14.2
    - 0.15.0
